### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by lpassos** [ethereum/eth-tester#89] opened 2018-05-09 14:55 UTC
* Version: 0.1.0b23
* Python: 3.6.4
* OS: MacOS Sierra 10.12.16

### What was wrong?

When using eth_tester as part of our test suite, I get some runtime errors as exemplified by the following stack trace:

```
    price,
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/contract.py:1311: in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/eth.py:244: in sendTransaction
    [transaction],
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/manager.py:103: in request_blocking
    response = self._make_request(method, params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/manager.py:86: in _make_request
    return request_func(method, params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py:18: in middleware
    return make_request(method, params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/formatting.py:21: in middleware
    response = make_request(method, formatted_params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/attrdict.py:18: in middleware
    response = make_request(method, params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/formatting.py:21: in middleware
    response = make_request(method, formatted_params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/normalize_errors.py:9: in middleware
    result = make_request(method, params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/validation.py:43: in middleware
    return make_request(method, post_validated_params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/formatting.py:21: in middleware
    response = make_request(method, formatted_params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/providers/eth_tester/middleware.py:320: in middleware
    return make_request(method, [filled_transaction] + params[1:])
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/fixture.py:12: in middleware
    return make_request(method, params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/middleware/formatting.py:21: in middleware
    response = make_request(method, formatted_params)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/providers/eth_tester/main.py:46: in make_request
    response = delegator(self.ethereum_tester, params)
cytoolz/functoolz.pyx:232: in cytoolz.functoolz.curry.__call__
    ???
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/providers/eth_tester/defaults.py:36: in call_eth_tester
    return getattr(eth_tester, fn_name)(*fn_args, **fn_kwargs)
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_tester/main.py:78: in func_wrapper
    self.mine_block()
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_tester/main.py:394: in mine_block
    block_hash = self.mine_blocks(1, coinbase=coinbase)[0]
../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_tester/main.py:389: in mine_blocks
    self._process_block_logs(block)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <eth_tester.main.EthereumTester object at 0x113774748>, block = {'difficulty': 131200, 'extra_data': '0x0000000000000000000000000000000000000000000000000000000000000000', 'gas_limit': 998051069, 'gas_used': 266681, ...}

    def _process_block_logs(self, block):
>       for _, filter in self._log_filters.items():
E       RuntimeError: dictionary changed size during iteration

../../../../.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_tester/main.py:401: RuntimeError
```

Ideas?

**Comment by pipermerriam** [comment] 2018-05-09 15:57
Is this a single threaded application?  Could there be another thread interacting with your `web3` instance?

**Comment by carver** [comment] 2018-05-09 20:44
> insights wrt possible race conditions using a shared web3 object.

It is not threadsafe. I would recommend having each thread initiate and use its own web3 object.

**Comment by pipermerriam** [comment] 2018-05-09 20:56
@lpassos alternatively, use something like asyncio which can generally be used for concurrency with code that is not threadsafe, but YMMV depending on your use case.  Closing as this is not a bug with eth-tester.

**Comment by pipermerriam** [comment] 2018-05-09 20:56
but feel free to continue conversation here.

**Closed by pipermerriam** 2018-05-09 20:56 UTC
