### ISSUE TITLE
On EthereumTesterProvider we can interact with the smart contract without deploying one

### ISSUE THREAD

**Issue by arjunaskykok** [ethereum/eth-tester#198] opened 2020-09-29 14:17 UTC
* Version: 0.5.0b2
* Python: 3.8
* OS: linux

### What was wrong?

```bash
(venv) $ pip install web3 py.evm eth-tester pytest
(venv) $ pip freeze
attrs==20.2.0
base58==2.0.1
bitarray==1.2.2
blake2b-py==0.1.3
cached-property==1.5.2
certifi==2020.6.20
chardet==3.0.4
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.3
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.0
eth-tester==0.5.0b2
eth-typing==2.2.2
eth-utils==1.9.5
hexbytes==0.2.1
idna==2.10
iniconfig==1.0.1
ipfshttpclient==0.6.1
jsonschema==3.2.0
lru-dict==1.1.6
multiaddr==0.0.9
mypy-extensions==0.4.3
netaddr==0.8.0
packaging==20.4
parsimonious==0.8.1
pluggy==0.13.1
protobuf==3.13.0
py==1.9.0
py-ecc==4.1.0
py-evm==0.3.0a19
pycryptodome==3.9.8
pyethash==0.1.27
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.1.0
requests==2.24.0
rlp==2.0.0a1
rusty-rlp==0.1.15
semantic-version==2.8.5
six==1.15.0
sortedcontainers==2.2.2
toml==0.10.1
toolz==0.11.1
trie==2.0.0a4
typing-extensions==3.7.4.3
urllib3==1.25.10
varint==1.0.2
web3==5.12.1
websockets==8.1
(venv) $ py.test test_simple_payment.py -s
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /tmp
plugins: web3-5.12.1
collected 1 item                                                               

test_simple_payment.py 

Balance of 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf on Universe A: 999997.9999999765146
Balance of 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf on Universe B: 1000000
Balance of 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf on Universe A: 999997.9999999765146
Balance of 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf on Universe B: 999995.9999999957872
.

============================== 1 passed in 0.56s ===============================

```

This is test_simple_payment.py

```python
from web3 import (
    EthereumTesterProvider,
    Web3,
)

bytecode = "6080604052336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550348015604f57600080fd5b5060618061005e6000396000f3fe608060405260043610601c5760003560e01c80631b9265b8146021575b600080fd5b60276029565b005b56fea2646970667358221220962c4ac975d366f08c2dae926afc5a9082cef680ca5bf042a1b48fcac2fd4aba64736f6c63430006090033"
abi = '[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"pay","outputs":[],"stateMutability":"payable","type":"function"}]'

import pytest

def test_pay():
    # Universe A
    w3_a = Web3(EthereumTesterProvider())
    # Universe B
    w3_b = Web3(EthereumTesterProvider())

    accounts_a = w3_a.eth.accounts
    accounts_b = w3_b.eth.accounts

    # Deploy contract to Universe A
    contract = w3_a.eth.contract(abi=abi, bytecode=bytecode)
    tx_hash = contract.constructor().transact({ "from": accounts_a[0], "gas": 899000, 'gasPrice': 200000 })
    contract_tx_receipt = w3_a.eth.waitForTransactionReceipt(tx_hash)

    # Execute smart contract method on Universe A
    payment_contract = w3_a.eth.contract(abi=abi, address=contract_tx_receipt.contractAddress)
    tx = { "from": accounts_a[0], "value": Web3.toWei(2, "ether"), "gas": 899000, 'gasPrice': 200000 }
    tx_hash = payment_contract.functions.pay().transact(tx)
    tx_receipt = w3_a.eth.waitForTransactionReceipt(tx_hash)

    balance1 = Web3.fromWei(w3_a.eth.getBalance(accounts_a[0]), "ether")
    balance2 = Web3.fromWei(w3_b.eth.getBalance(accounts_b[0]), "ether")
    print("\n")
    print(f"Balance of {accounts_a[0]} on Universe A: {balance1}")
    print(f"Balance of {accounts_b[0]} on Universe B: {balance2}")

    # Execute smart contract method on Universe B
    payment_contract = w3_b.eth.contract(abi=abi, address=contract_tx_receipt.contractAddress)
    tx = { "from": accounts_b[0], "value": Web3.toWei(4, "ether"), "gas": 899000, 'gasPrice': 200000 }
    tx_hash = payment_contract.functions.pay().transact(tx)
    tx_receipt = w3_b.eth.waitForTransactionReceipt(tx_hash)

    balance1 = Web3.fromWei(w3_a.eth.getBalance(accounts_a[0]), "ether")
    balance2 = Web3.fromWei(w3_b.eth.getBalance(accounts_b[0]), "ether")
    print(f"Balance of {accounts_a[0]} on Universe A: {balance1}")
    print(f"Balance of {accounts_b[0]} on Universe B: {balance2}")
```

The balance of the same address are different on one occasion. That's fine. Because a new universe is created with `EthereumTesterProvider()`. But if that's the case, why do we have the deployed contract on the universe B although the contract was deployed only on universe A?

**Comment by carver** [comment] 2020-09-29 17:02
Thanks for writing this up with the example, it helps understand what issue you're running into, and how you're approaching it.

>  why do we have the deployed contract on the universe B although the contract was deployed only on universe A?

I'm not yet convinced that this has happened. So far, all that's printing out is some balance changes, which could be explained in different ways. If you can show that the contract code is empty in both chains, then shows up in both chains immediately after deploying it in only one, then I'll help you look into it more.

**Comment by arjunaskykok** [comment] 2020-09-29 17:26
@carver After investigating it, apparently the problem is something else. I don't have to deploy the smart contract to be able to interact with the smart contract. Is this by design? It's weird. It caught me off guard.

As you can see below, I commented out the calling of constructor method.

```python
from web3 import (
    EthereumTesterProvider,
    Web3,
)

bytecode = "6080604052336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550348015604f57600080fd5b5060618061005e6000396000f3fe608060405260043610601c5760003560e01c80631b9265b8146021575b600080fd5b60276029565b005b56fea2646970667358221220962c4ac975d366f08c2dae926afc5a9082cef680ca5bf042a1b48fcac2fd4aba64736f6c63430006090033"
abi = '[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"pay","outputs":[],"stateMutability":"payable","type":"function"}]'

import pytest

def test_pay():
    w3_a = Web3(EthereumTesterProvider())

    accounts_a = w3_a.eth.accounts

    contract_address = "0xF2E246BB76DF876Cef8b38ae84130F4F55De395b"

    # Deploy contract to Universe A
    #contract = w3_a.eth.contract(abi=abi, bytecode=bytecode)
    #tx_hash = contract.constructor().transact({ "from": accounts_a[0], "gas": 899000, 'gasPrice': 200000 })
    #contract_tx_receipt = w3_a.eth.waitForTransactionReceipt(tx_hash)

    # Execute smart contract method on Universe A
    payment_contract = w3_a.eth.contract(abi=abi, address=contract_address)
    tx = { "from": accounts_a[0], "value": Web3.toWei(2, "ether"), "gas": 899000, 'gasPrice': 200000 }
    tx_hash = payment_contract.functions.pay().transact(tx)
    tx_receipt = w3_a.eth.waitForTransactionReceipt(tx_hash)

    balance = Web3.fromWei(w3_a.eth.getBalance(accounts_a[0]), "ether")
    print("\n")
    print(balance)
```

**Comment by carver** [comment] 2020-09-29 18:47
Invoking a contract just means sending a transaction to an address with the data field filled out. If there's no contract there, it will just send the funds, and the data will be ignored. Closing as not a bug, but feel free to comment here if you find that something different happened.

**Closed by carver** 2020-09-29 18:47 UTC

**Comment by arjunaskykok** [comment] 2020-10-01 09:57
You're right. The behavior is consistent in Ganache CLI. It's me who was careless when investigating the issue. I'm sorry.
