### ISSUE TITLE
Allow call method to query state of past blocks

### ISSUE THREAD

**Issue by bweick** [ethereum/eth-tester#47] opened 2018-01-13 02:21 UTC
### What was wrong?

Currently the eth-tester library doesn't support using the `eth_call` method to query the state of past blocks in the blockchain. Given that the new version of web3.py will support querying past blocks in the chain it makes sense to have that functionality available in eth-tester as well.

**Comment by carver** [comment] 2018-02-06 19:49
On a quick scan, it looks like `call` takes a `block_number` parameter in eth-tester, and in the backend:

- https://github.com/ethereum/eth-tester/blame/master/eth_tester/main.py#L406
- https://github.com/ethereum/eth-tester/blame/master/eth_tester/backends/pyevm/main.py#L436

But those have been there for a while, so if you ran into an error, we need a test to reproduce it.

**Comment by bweick** [comment] 2018-02-06 22:34
Looking at the function [here](https://github.com/ethereum/eth-tester/blame/master/eth_tester/backends/pyevm/main.py#L436) that you linked though it doesn't look like the call method actually uses that block number parameter on the backend. Some of the other `eth` methods reference a fxn called `_get_vm_for_block_number` though and then look like they are able to query state using the output of that.

**Comment by carver** [comment] 2018-02-07 01:29
> Looking at the function here that you linked though it doesn't look like the call method actually uses that block number parameter on the backend.

Ah yes, the hazards of a quick scan.


> Some of the other eth methods reference a fxn called _get_vm_for_block_number though and then look like they are able to query state using the output of that.

I think we just need to pass the optional block_number into `_execute_and_revert_transaction`:
https://github.com/ethereum/eth-tester/blame/master/eth_tester/backends/pyevm/main.py#L446

Would you like to take a crack at adding the test and the fix?

**Comment by bweick** [comment] 2018-02-07 05:25
Yeah for sure, the more involved the better!

**Comment by bweick** [comment] 2018-02-10 18:30
@carver I'm running into some issues here and was wondering if you could help clarify some stuff. So the problem I'm running into is writing the test to make sure the changes to eth-tester are correct. So I'm using the math contract and incrementing the counter then querying the state before the incrementation. However when I do that I run into an error where the nonce of the transaction being sent to query previous state (using the `call` method) doesn't match with the nonce of the sender account at that state, thus causing the function to error out. As long as one queries blocks that come after the latest transaction the `call` method works but anything before the transaction can't be queried (which obviously pretty much defeats the purpose). So I'm wondering if there's something I'm missing here or if there's additional logic that needs to be built into this?

**Comment by bweick** [comment] 2018-02-10 18:32
https://github.com/ethereum/py-evm/blob/9df7a3d02bc8a1a2d898d010c63ab7d567950d19/evm/vm/forks/frontier/validation.py#L26

Here is the line that the error is occurring in py-evm. I understand that a `call` is essentially a transaction that is reverted but doesn't treating it that way in this instance effectively make everything after a transaction is sent unqueriable? Thanks for any clarity you can provide!

**Comment by carver** [comment] 2018-02-12 18:34
> So I'm wondering if there's something I'm missing here or if there's additional logic that needs to be built into this?

Yes, it requires a bit of extra logic. Note that eth-tester is inferring the `nonce` here: https://github.com/ethereum/eth-tester/blob/master/eth_tester/backends/pyevm/main.py#L387

One solution is to check the transaction count at the state of the block that you want to call, and hard-wire the "transaction" to that nonce before doing the execute and revert.

**Comment by bweick** [comment] 2018-02-12 19:32
Great...thanks for the help. Fixed it up and [here](https://github.com/ethereum/eth-tester/pull/61) is the PR.

**Comment by carver** [comment] 2018-02-17 23:40
merged

**Closed by carver** 2018-02-17 23:40 UTC
