### ISSUE TITLE
Surprising execution behavior when calling smart contract functions

### ISSUE THREAD

**Issue by dspicher** [ethereum/eth-tester#260] opened 2023-06-21 14:47 UTC
* Version: 0.9.0b1
* Python: 3.11.3
* OS: linux

### What was wrong?

Consider the following contract `Reverter.sol`:
```solidity
pragma solidity 0.7.4;

contract Reverter {
    function revert_me() public {
        revert();
    }
}
```

When attempting to call the function by submitting a suitable transaction (see below), I observe that the revert is not actually triggered when calling `send_transaction` on the `EthereumTester` object. Only after doing an additional `call(tx)` (which to my understanding "simulates" the transaction) is the execution of the first transaction and its revert triggered. This despite the fact that I can observe the resulting transaction hash in mined blocks!

Is this local-caching-like behavior expected? And if so, can the execution be triggered through other means, rather than calling `call()`?

<details>
<summary>Reproducing Python code</summary>

```python

from pathlib import Path
from typing import Any

import solcx
from eth_abi import abi
from eth_tester import EthereumTester, PyEVMBackend
from eth_utils import encode_hex, function_abi_to_4byte_selector


def compile_source(path: Path) -> dict[str, Any]:
    return solcx.compile_files(
        [path],
        output_values=["abi", "bin", "storage-layout"],
    )[str(path) + ":" + path.stem]


REVERTER = compile_source(Path("Reverter.sol"))

eth_tester = EthereumTester(PyEVMBackend())

# adapted from https://github.com/ethereum/eth-tester/blob/6b9b74d986ebb76a4fdc3352309b2e1524bf66cf/eth_tester/utils/math_contract.py#L105-L118
def deploy_reverter() -> str:
    tx = {
        "from": eth_tester.get_accounts()[0],
        "gas": 100000,
        "data": encode_hex(bytes.fromhex(REVERTER["bin"])),
        "chain_id": 131277322940537,
    }
    tx_hash = eth_tester.send_transaction(tx)
    deploy_receipt = eth_tester.get_transaction_receipt(tx_hash)
    return deploy_receipt["contract_address"]

# adapted from https://github.com/ethereum/eth-tester/blob/6b9b74d986ebb76a4fdc3352309b2e1524bf66cf/eth_tester/utils/math_contract.py#L121-L134
def create_calling_tx(contract_address, fn_name, fn_args=None) -> dict[str, Any]:
    if fn_args is None:
        fn_args = tuple()
    fn_abi = next(filter(lambda f: f.get("name") == fn_name, REVERTER["abi"]))
    arg_types = [arg_abi["type"] for arg_abi in fn_abi["inputs"]]
    fn_selector = function_abi_to_4byte_selector(fn_abi)
    transaction = {
        "from": eth_tester.get_accounts()[0],
        "to": contract_address,
        "gas": 500000,
        "data": encode_hex(fn_selector + abi.encode(arg_types, fn_args)),
        "chain_id": 131277322940537,
    }
    return transaction


reverter_address = deploy_reverter()
tx = create_calling_tx(reverter_address, "revert_me")
# This line succeeds
tx_hash = eth_tester.send_transaction(tx)
# This line fails
eth_tester.call(tx)
```
</details>

**Comment by fselmo** [comment] 2023-06-21 17:51
If you check the transaction receipt for the `tx_hash` the `status` field should be `0` meaning it failed. This is expected behavior. If that's not the case then something else is going on. Please check that first.

**Comment by fselmo** [comment] 2023-06-28 20:49
@dspicher I'm going to close this but let me know if that is not the case (transaction status was `0`) and I can re-open. Can't reproduce this as of now.

**Closed by fselmo** 2023-06-28 20:49 UTC
